export {
  ALLOWED_CONSTANTS,
  ALLOWED_FUNCTIONS,
  MAX_AST_DEPTH,
  MAX_EXPRESSION_LENGTH,
  PARAM_MAX,
  PARAM_MIN,
  collectNames,
  compileExpression,
  evaluateAst,
  ExpressionSyntaxError,
  parseExpression,
  type AstNode,
} from "./parser";
export {
  annotationSpecSchema,
  defaultAnnotationSpec,
  defaultFunction2dSpec,
  defaultGeometrySpec,
  defaultImplicitSpec,
  defaultParametricSpec,
  defaultPolarSpec,
  defaultSpecForKind,
  defaultSurfaceSpec,
  defaultVectorFieldSpec,
  function2dSpecSchema,
  geometryShapes,
  geometrySpecSchema,
  implicitCurveSpecSchema,
  independentNames,
  parametricCurveSpecSchema,
  parseVisualizationSpec,
  polarCurveSpecSchema,
  safeParseVisualizationSpec,
  specWithUserExpressions,
  surfaceSpecSchema,
  vectorFieldSpecSchema,
  visualizationKinds,
  visualizationSpecSchema,
  type AnnotationSpec,
  type Function2dSpec,
  type GeometryShape,
  type GeometrySpec,
  type ImplicitCurveSpec,
  type ParametricCurveSpec,
  type PolarCurveSpec,
  type SurfaceSpec,
  type UserExpressionFields,
  type VectorFieldSpec,
  type VisualizationKind,
  type VisualizationSpec,
} from "./spec";
export { parseSceneDocument, sceneFromLayers, layerColor, LAYER_COLORS, MAX_LAYERS, sceneDocumentSchema, type SceneDocument } from "./scene";
export {
  EXAMPLES,
  KIND_LABELS,
  exampleById,
  examplesForKind,
  starterForKind,
  type ExampleItem,
} from "./examples";
export {
  CAPABILITIES,
  assertCapabilityCoverage,
  capabilityFor,
  type Capability,
  type SupportLevel,
} from "./capabilities";
export { sampleExplicitSurface, type SurfaceMesh, type SurfaceSampler } from "./sampling";
